export const apiDocsMarkdown = [
  "# Emaal Wallet API v1",
  "",
  "Base URL: `https://api.emaal.example/v1`",
  "",
  "## Authentication",
  "",
  "Every request requires an API key issued by an Emaal admin:",
  "",
  "```",
  "Authorization: Bearer emaal_live_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "```",
  "",
  "Keys are shown once at creation time and are never recoverable — only re-issuable.",
  "Each key carries one or more scopes; a request whose key lacks the required",
  "scope is rejected with 403.",
  "",
  "## Scopes",
  "",
  "| Scope | Grants |",
  "| --- | --- |",
  "| `balance:read` | Look up whether a phone number has an Emaal wallet |",
  "| `transaction:read` | Read the status of your own transactions |",
  "| `transfer:write` | Send payouts from your settlement balance to a customer wallet |",
  "",
  "## Rate limiting",
  "",
  "Each partner has a per-minute request cap (default 120/min, configurable by",
  "an admin). Exceeding it returns `429` with `{\"error\": {\"code\": \"rate_limited\"}}`.",
  "",
  "## Idempotency",
  "",
  "`POST /payouts` requires a client-generated `idempotencyKey` (UUID). Retrying",
  "the same key returns the original result instead of creating a duplicate payout.",
  "",
  "## Endpoints",
  "",
  "### `GET /v1/wallets/:phone`",
  "Scope: `balance:read`. Returns `{ \"found\": boolean, \"name\"?: string }`.",
  "",
  "### `GET /v1/transactions/:id`",
  "Scope: `transaction:read`. Returns the transaction if it belongs to your partner account.",
  "",
  "### `POST /v1/payouts`",
  "Scope: `transfer:write`. Body: `{ \"toPhone\": string, \"amountUsd\": number, \"idempotencyKey\": string }`.",
  "Debits your settlement balance and credits the named customer's wallet. An",
  "admin funds your settlement balance from the Emaal admin console.",
  "",
  "## Webhooks",
  "",
  "If a webhook URL is configured, Emaal POSTs a signed `transaction.updated`",
  "event on every status change for your transactions:",
  "",
  "```",
  "X-Emaal-Signature: hex(hmac_sha256(body, your_webhook_secret))",
  "```",
  "",
  "Verify the signature before trusting the payload. Non-2xx responses are",
  "retried up to 5 times with the delivery marked `FAILED` after the final attempt.",
  "",
].join("\n");
